name: Deploy to second repo
on:
  workflow_dispatch:

jobs:
  main:
    name: Git push on separate repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: '[DEBUG] Repo Status'
        run: |
          ls -la /home/runner/work/ -I _*
          echo "-----------------"
          pwd
          ls -la
          echo "-----------------"
          cat README.md


      - name: Checkout pong-repo
        uses: actions/checkout@v4
        with:
          repository: AndBroCorp/test-pong
          ref: 'main'
          ssh-key: ${{ secrets.PONG_DEPLOY_TOKEN }}
          path: '.tmp/'

      - name: '[DEBUG] Repo Status (pong-repo)'
        run: |
          ls -la /home/runner/work/ -I _*
          echo "-----------------"
          pwd
          ls -la 
          echo "-----------------"
          ls -la /home/runner/work/test-ping/test-ping/.tmp/
          echo "-----------------"
          cat README.md

      - name: Setup Config
        run: |
          cd .tmp/pong-repo/
          git config user.name "GitHub Actions Bot"
          git config user.email "andreas.brostrom+test-ping-pong@playipp.com"

      - name: Sync files
        run: |
          cp -r src/* .tmp/pong-repo/.
          cd .tmp/pong-repo
          git add *
          git commit -m "Sync from ping repo"
          git push origin main
