name: Deploy to second repo
on:
  workflow_dispatch:

jobs:
  main:
    name: Git push on separate repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Repo Status
        run: |
          pwd
          ls
          cat README.md

      - name: Checkout pong-repo
        uses: actions/checkout@v4
        with:
          repository: AndBroCorp/test-pong
          ref: 'main'
          ssh-key: ${{ secrets.PONG_DEPLOY_TOKEN }}

      - name: Repo Status
        run: |
          ls ../
          pwd
          ls
          cat README.md

      - name: Setup Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "andreas.brostrom+test-ping-pong@playipp.com"

      - name: Sync files
        run: |
          cp -r /home/runner/work/test-ping/src/* pong-repo/.
          cd pong-repo
          git add *
          git commit -m "Sync from ping repo"
          git push origin main
