name: Deploy to second repo
on:
  workflow_dispatch:

jobs:
  main:
    name: Git push on separate repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: '[DEBUG] Repo Status'
        run: |
          ls -la ../
          pwd
          ls -la
          cat README.md

      - name: Prep Payload
        run: |
          mkdir -p .tmp
          zip -r /home/runner/work/payload.zip src

      - name: Checkout pong-repo
        uses: actions/checkout@v4
        with:
          repository: AndBroCorp/test-pong
          ref: 'main'
          ssh-key: ${{ secrets.PONG_DEPLOY_TOKEN }}
          path: '.tmp'

      - name: '[DEBUG] Repo Status (pong-repo)'
        run: |
          ls -la ../
          pwd
          ls -la 
          cat README.md

      - name: Setup Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "andreas.brostrom+test-ping-pong@playipp.com"

      - name: Sync files
        run: |
          cp -r /home/runner/work/test-ping/src/* pong-repo/.
          cd pong-repo
          git add *
          git commit -m "Sync from ping repo"
          git push origin main
