name: Deploy to second repo
on:
  workflow_dispatch:

jobs:
  main:
    name: Git push on separate repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup git config
        run: |
          pwd
          ls
          cat README.md

      - name: Checkout pong-repo
        uses: actions/checkout@v4
        with:
          repository: AndBroCorp/test-pong
          ref: 'main'
          ssh-key: ${{ secrets.PONG_DEPLOY_TOKEN }}

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "andreas.brostrom+test-ping-pong@playipp.com"
          pwd
          ls
          cat README.md
